//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangOnline.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BANHANGONLINEEntities5 : DbContext
    {
        public BANHANGONLINEEntities5()
            : base("name=BANHANGONLINEEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DONDH> DONDHs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAISP> LOAISPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHASANXUAT> NHASANXUATs { get; set; }
        public virtual DbSet<PHIEUXUAT> PHIEUXUATs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
    
        public virtual int sp_SuaDonDathang(Nullable<int> mASP, Nullable<int> mAKH, Nullable<int> mANV, Nullable<int> sLD, Nullable<decimal> tHANHTIEN, Nullable<System.DateTime> nGAYDH, Nullable<int> mADH)
        {
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var sLDParameter = sLD.HasValue ?
                new ObjectParameter("SLD", sLD) :
                new ObjectParameter("SLD", typeof(int));
    
            var tHANHTIENParameter = tHANHTIEN.HasValue ?
                new ObjectParameter("THANHTIEN", tHANHTIEN) :
                new ObjectParameter("THANHTIEN", typeof(decimal));
    
            var nGAYDHParameter = nGAYDH.HasValue ?
                new ObjectParameter("NGAYDH", nGAYDH) :
                new ObjectParameter("NGAYDH", typeof(System.DateTime));
    
            var mADHParameter = mADH.HasValue ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaDonDathang", mASPParameter, mAKHParameter, mANVParameter, sLDParameter, tHANHTIENParameter, nGAYDHParameter, mADHParameter);
        }
    
        public virtual int sp_SuaKhachHang(string hOTEN, Nullable<System.DateTime> nGAYSINH, string gIOITINH, string dIENTHOAI, string mAIL, string dIACHI, Nullable<System.DateTime> nGAYDK, Nullable<int> mAKH)
        {
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var dIENTHOAIParameter = dIENTHOAI != null ?
                new ObjectParameter("DIENTHOAI", dIENTHOAI) :
                new ObjectParameter("DIENTHOAI", typeof(string));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var nGAYDKParameter = nGAYDK.HasValue ?
                new ObjectParameter("NGAYDK", nGAYDK) :
                new ObjectParameter("NGAYDK", typeof(System.DateTime));
    
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaKhachHang", hOTENParameter, nGAYSINHParameter, gIOITINHParameter, dIENTHOAIParameter, mAILParameter, dIACHIParameter, nGAYDKParameter, mAKHParameter);
        }
    
        public virtual int sp_SuaLoaiSanPham(string tENLOAI, string dVT, Nullable<int> mALOAI)
        {
            var tENLOAIParameter = tENLOAI != null ?
                new ObjectParameter("TENLOAI", tENLOAI) :
                new ObjectParameter("TENLOAI", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var mALOAIParameter = mALOAI.HasValue ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaLoaiSanPham", tENLOAIParameter, dVTParameter, mALOAIParameter);
        }
    
        public virtual int sp_SuaNhanVien(string hOTEN, Nullable<System.DateTime> nGAYSINH, string gIOITINH, string dIENTHOAI, string mAIL, string dIACHI, Nullable<System.DateTime> nGAYLAM, Nullable<decimal> lUONG, string uSERNAMES, string pASSWORDS, Nullable<int> tRANGTHAI, Nullable<int> mANV)
        {
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var dIENTHOAIParameter = dIENTHOAI != null ?
                new ObjectParameter("DIENTHOAI", dIENTHOAI) :
                new ObjectParameter("DIENTHOAI", typeof(string));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var nGAYLAMParameter = nGAYLAM.HasValue ?
                new ObjectParameter("NGAYLAM", nGAYLAM) :
                new ObjectParameter("NGAYLAM", typeof(System.DateTime));
    
            var lUONGParameter = lUONG.HasValue ?
                new ObjectParameter("LUONG", lUONG) :
                new ObjectParameter("LUONG", typeof(decimal));
    
            var uSERNAMESParameter = uSERNAMES != null ?
                new ObjectParameter("USERNAMES", uSERNAMES) :
                new ObjectParameter("USERNAMES", typeof(string));
    
            var pASSWORDSParameter = pASSWORDS != null ?
                new ObjectParameter("PASSWORDS", pASSWORDS) :
                new ObjectParameter("PASSWORDS", typeof(string));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(int));
    
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaNhanVien", hOTENParameter, nGAYSINHParameter, gIOITINHParameter, dIENTHOAIParameter, mAILParameter, dIACHIParameter, nGAYLAMParameter, lUONGParameter, uSERNAMESParameter, pASSWORDSParameter, tRANGTHAIParameter, mANVParameter);
        }
    
        public virtual int sp_SuaNhaSanXuat(string tENSX, string qUOCGIA, Nullable<int> mASX)
        {
            var tENSXParameter = tENSX != null ?
                new ObjectParameter("TENSX", tENSX) :
                new ObjectParameter("TENSX", typeof(string));
    
            var qUOCGIAParameter = qUOCGIA != null ?
                new ObjectParameter("QUOCGIA", qUOCGIA) :
                new ObjectParameter("QUOCGIA", typeof(string));
    
            var mASXParameter = mASX.HasValue ?
                new ObjectParameter("MASX", mASX) :
                new ObjectParameter("MASX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaNhaSanXuat", tENSXParameter, qUOCGIAParameter, mASXParameter);
        }
    
        public virtual int sp_SuaPhieuXuat(Nullable<int> mASP, Nullable<int> mAKH, Nullable<int> mANV, Nullable<int> mADH, Nullable<int> sLX, Nullable<decimal> tHANHTIEN, Nullable<System.DateTime> nGAYXUAT, Nullable<int> mAPX)
        {
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var mADHParameter = mADH.HasValue ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(int));
    
            var sLXParameter = sLX.HasValue ?
                new ObjectParameter("SLX", sLX) :
                new ObjectParameter("SLX", typeof(int));
    
            var tHANHTIENParameter = tHANHTIEN.HasValue ?
                new ObjectParameter("THANHTIEN", tHANHTIEN) :
                new ObjectParameter("THANHTIEN", typeof(decimal));
    
            var nGAYXUATParameter = nGAYXUAT.HasValue ?
                new ObjectParameter("NGAYXUAT", nGAYXUAT) :
                new ObjectParameter("NGAYXUAT", typeof(System.DateTime));
    
            var mAPXParameter = mAPX.HasValue ?
                new ObjectParameter("MAPX", mAPX) :
                new ObjectParameter("MAPX", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaPhieuXuat", mASPParameter, mAKHParameter, mANVParameter, mADHParameter, sLXParameter, tHANHTIENParameter, nGAYXUATParameter, mAPXParameter);
        }
    
        public virtual int sp_SuaSanPham(string tENSP, Nullable<decimal> gIA, string cHITIET, string iMAGES, Nullable<int> tRANGTHAI, Nullable<decimal> gIAMGIA, Nullable<int> sL, Nullable<int> mALOAI, Nullable<int> mASP)
        {
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(decimal));
    
            var cHITIETParameter = cHITIET != null ?
                new ObjectParameter("CHITIET", cHITIET) :
                new ObjectParameter("CHITIET", typeof(string));
    
            var iMAGESParameter = iMAGES != null ?
                new ObjectParameter("IMAGES", iMAGES) :
                new ObjectParameter("IMAGES", typeof(string));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(int));
    
            var gIAMGIAParameter = gIAMGIA.HasValue ?
                new ObjectParameter("GIAMGIA", gIAMGIA) :
                new ObjectParameter("GIAMGIA", typeof(decimal));
    
            var sLParameter = sL.HasValue ?
                new ObjectParameter("SL", sL) :
                new ObjectParameter("SL", typeof(int));
    
            var mALOAIParameter = mALOAI.HasValue ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaSanPham", tENSPParameter, gIAParameter, cHITIETParameter, iMAGESParameter, tRANGTHAIParameter, gIAMGIAParameter, sLParameter, mALOAIParameter, mASPParameter);
        }
    
        public virtual int sp_ThemDonDatHang(Nullable<int> mASP, Nullable<int> mAKH, Nullable<int> mANV, Nullable<int> sLD, Nullable<decimal> tHANHTIEN, Nullable<System.DateTime> nGAYDH)
        {
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var sLDParameter = sLD.HasValue ?
                new ObjectParameter("SLD", sLD) :
                new ObjectParameter("SLD", typeof(int));
    
            var tHANHTIENParameter = tHANHTIEN.HasValue ?
                new ObjectParameter("THANHTIEN", tHANHTIEN) :
                new ObjectParameter("THANHTIEN", typeof(decimal));
    
            var nGAYDHParameter = nGAYDH.HasValue ?
                new ObjectParameter("NGAYDH", nGAYDH) :
                new ObjectParameter("NGAYDH", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDonDatHang", mASPParameter, mAKHParameter, mANVParameter, sLDParameter, tHANHTIENParameter, nGAYDHParameter);
        }
    
        public virtual int sp_ThemKhachHang(string hOTEN, Nullable<System.DateTime> nGAYSINH, string gIOITINH, string dIENTHOAI, string mAIL, string dIACHI, Nullable<System.DateTime> nGAYDK)
        {
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var dIENTHOAIParameter = dIENTHOAI != null ?
                new ObjectParameter("DIENTHOAI", dIENTHOAI) :
                new ObjectParameter("DIENTHOAI", typeof(string));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var nGAYDKParameter = nGAYDK.HasValue ?
                new ObjectParameter("NGAYDK", nGAYDK) :
                new ObjectParameter("NGAYDK", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemKhachHang", hOTENParameter, nGAYSINHParameter, gIOITINHParameter, dIENTHOAIParameter, mAILParameter, dIACHIParameter, nGAYDKParameter);
        }
    
        public virtual int sp_ThemLoaiSanPham(string tENLOAI, string dVT)
        {
            var tENLOAIParameter = tENLOAI != null ?
                new ObjectParameter("TENLOAI", tENLOAI) :
                new ObjectParameter("TENLOAI", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLoaiSanPham", tENLOAIParameter, dVTParameter);
        }
    
        public virtual int sp_ThemNhanVien(string hOTEN, Nullable<System.DateTime> nGAYSINH, string gIOITINH, string dIENTHOAI, string mAIL, string dIACHI, Nullable<System.DateTime> nGAYLAM, Nullable<decimal> lUONG, string uSERNAMES, string pASSWORDS, Nullable<int> tRANGTHAI)
        {
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var dIENTHOAIParameter = dIENTHOAI != null ?
                new ObjectParameter("DIENTHOAI", dIENTHOAI) :
                new ObjectParameter("DIENTHOAI", typeof(string));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var nGAYLAMParameter = nGAYLAM.HasValue ?
                new ObjectParameter("NGAYLAM", nGAYLAM) :
                new ObjectParameter("NGAYLAM", typeof(System.DateTime));
    
            var lUONGParameter = lUONG.HasValue ?
                new ObjectParameter("LUONG", lUONG) :
                new ObjectParameter("LUONG", typeof(decimal));
    
            var uSERNAMESParameter = uSERNAMES != null ?
                new ObjectParameter("USERNAMES", uSERNAMES) :
                new ObjectParameter("USERNAMES", typeof(string));
    
            var pASSWORDSParameter = pASSWORDS != null ?
                new ObjectParameter("PASSWORDS", pASSWORDS) :
                new ObjectParameter("PASSWORDS", typeof(string));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", hOTENParameter, nGAYSINHParameter, gIOITINHParameter, dIENTHOAIParameter, mAILParameter, dIACHIParameter, nGAYLAMParameter, lUONGParameter, uSERNAMESParameter, pASSWORDSParameter, tRANGTHAIParameter);
        }
    
        public virtual int sp_ThemNhaSanXuat(string tENSX, string qUOCGIA)
        {
            var tENSXParameter = tENSX != null ?
                new ObjectParameter("TENSX", tENSX) :
                new ObjectParameter("TENSX", typeof(string));
    
            var qUOCGIAParameter = qUOCGIA != null ?
                new ObjectParameter("QUOCGIA", qUOCGIA) :
                new ObjectParameter("QUOCGIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhaSanXuat", tENSXParameter, qUOCGIAParameter);
        }
    
        public virtual int sp_ThemPhieuXuat(Nullable<int> mAKH, Nullable<int> mASP, Nullable<int> mANV, Nullable<int> mADH, Nullable<int> sLX, Nullable<decimal> tHANHTIEN, Nullable<System.DateTime> nGAYXUAT)
        {
            var mAKHParameter = mAKH.HasValue ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(int));
    
            var mASPParameter = mASP.HasValue ?
                new ObjectParameter("MASP", mASP) :
                new ObjectParameter("MASP", typeof(int));
    
            var mANVParameter = mANV.HasValue ?
                new ObjectParameter("MANV", mANV) :
                new ObjectParameter("MANV", typeof(int));
    
            var mADHParameter = mADH.HasValue ?
                new ObjectParameter("MADH", mADH) :
                new ObjectParameter("MADH", typeof(int));
    
            var sLXParameter = sLX.HasValue ?
                new ObjectParameter("SLX", sLX) :
                new ObjectParameter("SLX", typeof(int));
    
            var tHANHTIENParameter = tHANHTIEN.HasValue ?
                new ObjectParameter("THANHTIEN", tHANHTIEN) :
                new ObjectParameter("THANHTIEN", typeof(decimal));
    
            var nGAYXUATParameter = nGAYXUAT.HasValue ?
                new ObjectParameter("NGAYXUAT", nGAYXUAT) :
                new ObjectParameter("NGAYXUAT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemPhieuXuat", mAKHParameter, mASPParameter, mANVParameter, mADHParameter, sLXParameter, tHANHTIENParameter, nGAYXUATParameter);
        }
    
        public virtual int sp_ThemSanPham(string tENSP, Nullable<decimal> gIA, string cHITIET, string iMAGES, Nullable<int> tRANGTHAI, Nullable<decimal> gIAMGIA, Nullable<int> sL, Nullable<int> mASX, Nullable<int> mALOAI)
        {
            var tENSPParameter = tENSP != null ?
                new ObjectParameter("TENSP", tENSP) :
                new ObjectParameter("TENSP", typeof(string));
    
            var gIAParameter = gIA.HasValue ?
                new ObjectParameter("GIA", gIA) :
                new ObjectParameter("GIA", typeof(decimal));
    
            var cHITIETParameter = cHITIET != null ?
                new ObjectParameter("CHITIET", cHITIET) :
                new ObjectParameter("CHITIET", typeof(string));
    
            var iMAGESParameter = iMAGES != null ?
                new ObjectParameter("IMAGES", iMAGES) :
                new ObjectParameter("IMAGES", typeof(string));
    
            var tRANGTHAIParameter = tRANGTHAI.HasValue ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(int));
    
            var gIAMGIAParameter = gIAMGIA.HasValue ?
                new ObjectParameter("GIAMGIA", gIAMGIA) :
                new ObjectParameter("GIAMGIA", typeof(decimal));
    
            var sLParameter = sL.HasValue ?
                new ObjectParameter("SL", sL) :
                new ObjectParameter("SL", typeof(int));
    
            var mASXParameter = mASX.HasValue ?
                new ObjectParameter("MASX", mASX) :
                new ObjectParameter("MASX", typeof(int));
    
            var mALOAIParameter = mALOAI.HasValue ?
                new ObjectParameter("MALOAI", mALOAI) :
                new ObjectParameter("MALOAI", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemSanPham", tENSPParameter, gIAParameter, cHITIETParameter, iMAGESParameter, tRANGTHAIParameter, gIAMGIAParameter, sLParameter, mASXParameter, mALOAIParameter);
        }
    }
}
