//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangOnline.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.DONDHs = new HashSet<DONDH>();
            this.PHIEUXUATs = new HashSet<PHIEUXUAT>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public string CHITIET { get; set; }
        public string IMAGES { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public Nullable<decimal> GIAMGIA { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<int> MASX { get; set; }
        public Nullable<int> MALOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDH> DONDHs { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUXUAT> PHIEUXUATs { get; set; }
    }
}
